server:
  port: 9091
spring:
  #  main:
  #    web-application-type: none
  application:
    name: ftps-file-transfer-service

eureka:
  instance:
    hostname: ${hostname:127.0.0.1}
    #eureka界面显示服务名
    instance-id: ${spring.application.name}
    #是否显示访问的IP地址
    prefer-ip-address: true
    #eureka客户端像服务端发送心跳的时间间隔 单位是秒（默认值为30秒）
    lease-renewal-interval-in-seconds: 30
    #eureka服务端收到最后一次心跳等待时间上限，单位是秒（默认值为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    healthcheck:
      enabled: true
    eureka-server-read-timeout-seconds: 60
    #表识不向注册中心注册自己
    register-with-eureka: true
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka/
      server:
        enable-self-preservation : false
        eviction-interval-timer-in-ms: 2000